// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dccslmmhqrzrxglinoei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjY3NsbW1ocXJ6cnhnbGlub2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5ODU2NzIsImV4cCI6MjA4NzU2MTY3Mn0.96PYoKgmyk9QECtDlGEBW4_xAEwso51_myH3L0cme1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});